/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);

// src/Plugin.ts
var import_obsidian2 = require("obsidian");

// src/PluginSettingsTab.ts
var import_obsidian = require("obsidian");
var blurLevels = {
  off: "0px",
  low: "5px",
  high: "15px"
};
var positionOptions = {
  "center": "Center",
  "top": "Top",
  "bottom": "Bottom",
  "left": "Left",
  "right": "Right",
  "top left": "Top left",
  "top right": "Top right",
  "bottom left": "Bottom left",
  "bottom right": "Bottom right"
};
var sizeOptions = {
  "cover": "Fill (crop to cover)",
  "contain": "Fit (show whole image)",
  "100% 100%": "Stretch",
  "auto": "Actual size"
};
var UrlSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const instructions = containerEl.createEl("div");
    instructions.createEl("p", { text: "The URL needs to be a remote resource. Local files are not yet supported." });
    instructions.createEl("p", { text: "The other options, like opacity, blur, and input contrast, are helpers to tweak your experience." });
    instructions.createEl("a", { href: "https://github.com/shmolf/obsidian-editor-background/issues", text: "Submit an issue" });
    new import_obsidian.Setting(containerEl).setName("Background image URL").setDesc("URL for the background image to load.").addText(
      (text) => text.setPlaceholder("https://example.com/image.png").setValue(this.plugin.settings.imageUrl).onChange(async (value) => {
        this.plugin.settings.imageUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Dark theme image URL").setDesc("Optional. When set, this image is used while the dark theme is active, and the URL above is used for the light theme.").addText(
      (text) => text.setPlaceholder("https://example.com/dark-image.png").setValue(this.plugin.settings.darkImageUrl).onChange(async (value) => {
        this.plugin.settings.darkImageUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Background opacity").setDesc("Opacity of the background image, between 0% and 100%.").addSlider(
      (slider) => {
        var _a;
        return slider.setLimits(0, 100, 1).setValue(this.floatToPercent((_a = this.plugin.settings.opacity) != null ? _a : DEFAULT_SETTINGS.opacity)).setDynamicTooltip().onChange(async (value) => {
          this.plugin.settings.opacity = this.percentToFloat(value);
          await this.plugin.saveSettings();
        });
      }
    );
    new import_obsidian.Setting(containerEl).setName("Image blur").setDesc("Increasing the blur can help make the text more legible.").addDropdown((dropdown) => {
      dropdown.addOption(blurLevels.off, "Off").addOption(blurLevels.low, "Low").addOption(blurLevels.high, "High").setValue(this.plugin.settings.bluriness).onChange(async (value) => {
        this.plugin.settings.bluriness = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Input area contrast background").setDesc("Adds a translucent background behind the input area, to help improve legibility.").addToggle((toggle) => {
      toggle.setTooltip("Enable to increase the contrast of the input area.").setValue(this.plugin.settings.inputContrast).onChange(async (value) => {
        this.plugin.settings.inputContrast = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Image position").setDesc("Reposition the image in cases where the focus is not centered.").addDropdown((dropdown) => {
      Object.entries(positionOptions).forEach(([key, value]) => dropdown.addOption(key, value));
      dropdown.setValue(this.plugin.settings.position).onChange(async (value) => {
        this.plugin.settings.position = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Image scaling").setDesc("How the image is scaled to the available space.").addDropdown((dropdown) => {
      Object.entries(sizeOptions).forEach(([key, value]) => dropdown.addOption(key, value));
      dropdown.setValue(this.plugin.settings.size).onChange(async (value) => {
        this.plugin.settings.size = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Apply to entire window").setDesc("Show a single background image behind the whole window, including the sidebars, instead of a separate image in each pane.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.wholeWindow).onChange(async (value) => {
        this.plugin.settings.wholeWindow = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Excluded paths").setDesc('Notes matching these vault paths will not show the background image. One folder or note path per line, e.g. "Daily Notes" or "Projects/Todo.md".').addTextArea((text) => {
      text.setPlaceholder("Daily Notes\nProjects/Todo.md").setValue(this.plugin.settings.excludedPaths).onChange(async (value) => {
        this.plugin.settings.excludedPaths = value;
        await this.plugin.saveSettings();
      });
    });
  }
  floatToPercent(value) {
    return Math.round(Math.max(0, Math.min(1, value)) * 100);
  }
  percentToFloat(value) {
    return Math.max(0, Math.min(100, value)) / 100;
  }
};

// src/Plugin.ts
var DEFAULT_SETTINGS = {
  imageUrl: "",
  darkImageUrl: "",
  opacity: 0.3,
  bluriness: "5px",
  inputContrast: false,
  position: "center",
  size: "cover",
  wholeWindow: false,
  excludedPaths: ""
};
var LEGACY_PLACEHOLDER_URL = "protocol://domain.tld/path/to/image.png";
var LEGACY_BLUR_LEVELS = { off: "0px", low: "5px", high: "15px" };
var CSS_PROPERTIES = [
  "--obsidian-editor-background-image",
  "--obsidian-editor-background-opacity",
  "--obsidian-editor-background-bluriness",
  "--obsidian-editor-background-input-contrast",
  "--obsidian-editor-background-line-padding",
  "--obsidian-editor-background-position",
  "--obsidian-editor-background-size"
];
var WHOLE_WINDOW_CLASS = "editor-background-whole-window";
var EXCLUDED_CLASS = "editor-background-excluded";
var BackgroundPlugin2 = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.managedDocs = /* @__PURE__ */ new Set();
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new UrlSettingsTab(this.app, this));
    this.app.workspace.onLayoutReady(() => this.updateAllBackgrounds());
    this.registerEvent(
      this.app.workspace.on("window-open", (win) => this.updateBackground(win.doc))
    );
    this.registerEvent(this.app.workspace.on("css-change", () => this.updateAllBackgrounds()));
    this.registerEvent(this.app.workspace.on("layout-change", () => this.applyExclusions()));
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => this.applyExclusions()));
  }
  onunload() {
    this.managedDocs.forEach((doc) => this.clearBackground(doc));
    this.managedDocs.clear();
    this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      leaf.view.containerEl.removeClass(EXCLUDED_CLASS);
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (this.settings.imageUrl === LEGACY_PLACEHOLDER_URL) {
      this.settings.imageUrl = "";
    }
    if (this.settings.bluriness in LEGACY_BLUR_LEVELS) {
      this.settings.bluriness = LEGACY_BLUR_LEVELS[this.settings.bluriness];
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.updateAllBackgrounds();
  }
  updateAllBackgrounds() {
    this.managedDocs.add(document);
    this.managedDocs.forEach((doc) => this.updateBackground(doc));
    this.applyExclusions();
  }
  updateBackground(doc = activeDocument) {
    this.managedDocs.add(doc);
    const isDarkTheme = doc.body.hasClass("theme-dark");
    const darkUrl = this.settings.darkImageUrl.trim();
    const url = (isDarkTheme && darkUrl.length > 0 ? darkUrl : this.settings.imageUrl).trim();
    const image = url.length > 0 ? `url("${url.replace(/"/g, '\\"')}")` : "none";
    doc.body.style.setProperty("--obsidian-editor-background-image", image);
    doc.body.style.setProperty("--obsidian-editor-background-opacity", `${this.settings.opacity}`);
    doc.body.style.setProperty("--obsidian-editor-background-bluriness", `blur(${this.settings.bluriness})`);
    doc.body.style.setProperty("--obsidian-editor-background-input-contrast", this.settings.inputContrast ? "#ffffff17" : "none");
    doc.body.style.setProperty("--obsidian-editor-background-line-padding", this.settings.inputContrast ? "1rem" : "0");
    doc.body.style.setProperty("--obsidian-editor-background-position", this.settings.position);
    doc.body.style.setProperty("--obsidian-editor-background-size", this.settings.size);
    doc.body.toggleClass(WHOLE_WINDOW_CLASS, this.settings.wholeWindow);
  }
  clearBackground(doc) {
    CSS_PROPERTIES.forEach((property) => doc.body.style.removeProperty(property));
    doc.body.removeClass(WHOLE_WINDOW_CLASS);
  }
  applyExclusions() {
    const prefixes = this.settings.excludedPaths.split("\n").map((path) => path.trim()).filter((path) => path.length > 0).map((path) => (0, import_obsidian2.normalizePath)(path));
    this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      var _a, _b;
      const view = leaf.view;
      if (!(view instanceof import_obsidian2.MarkdownView))
        return;
      const path = (_b = (_a = view.file) == null ? void 0 : _a.path) != null ? _b : "";
      const excluded = path.length > 0 && prefixes.some((prefix) => path === prefix || path.startsWith(`${prefix}/`));
      view.containerEl.toggleClass(EXCLUDED_CLASS, excluded);
    });
  }
};

// main.ts
var main_default = BackgroundPlugin2;

/* nosourcemap */